apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
  labels:
    app: lanchonete-soat7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete-soat7
  template:
    metadata:
      labels:
        app: lanchonete-soat7
    spec:
      containers:
        - name: lanchonete
          image: 737021845667.dkr.ecr.us-east-1.amazonaws.com/soat7-lanchonete:1.0.1
          ports:
            - containerPort: 8080
          env:
            -
              name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: db
            -
              name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: username
            -
              name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: password