server:
  port: 8081

spring:
  profiles:
    active: ${APP_ENV}

---

spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:tech}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
---
pedido:
  url: "http://localhost:8081/rest/api/v1/"
